DROP FUNCTION IF EXISTS unspent_output_deferred(text);
DROP FUNCTION IF EXISTS unspent_output_deferred_bitmask(text);
DROP FUNCTION IF EXISTS unspent_output_deferred_marker(text);
DROP FUNCTION IF EXISTS unspent_deferred_released_spends(text, text);
DROP FUNCTION IF EXISTS unspent_deferred_dirty_creators(text);
DROP FUNCTION IF EXISTS unspent_deferred_recent_spends(text);
DROP FUNCTION IF EXISTS unspent_deferred_dirty_transactions(text);
DROP FUNCTION IF EXISTS unspent_deferred_read_tier(text);
DROP FUNCTION IF EXISTS unspent_deferred_backfill(text, bytea, bytea);
DROP FUNCTION IF EXISTS unspent_deferred_run_batch(text, bigint, bigint, integer, integer, integer, integer, bigint, boolean);
DROP FUNCTION IF EXISTS unspent_deferred_initialize(text, bigint, bigint);
DROP FUNCTION IF EXISTS unspent_deferred_recompute_bits();
DROP FUNCTION IF EXISTS unspent_deferred_recompute_marker();
DROP FUNCTION IF EXISTS unspent_deferred_any_acceptance(bigint);
DROP FUNCTION IF EXISTS unspent_deferred_acceptance_bits(bigint);
DROP TRIGGER IF EXISTS trigger_unspent_deferred_node_block_delete ON node_block;
DROP TRIGGER IF EXISTS trigger_unspent_deferred_node_transaction_delete ON node_transaction;
DROP FUNCTION IF EXISTS trigger_unspent_deferred_node_block_delete();
DROP FUNCTION IF EXISTS trigger_unspent_deferred_node_transaction_delete();
DROP TABLE IF EXISTS unspent_tracking_watch;
DROP TABLE IF EXISTS unspent_tracking_progress;
DROP TABLE IF EXISTS unspent_tracking_events;
-- Partial indexes created by the agent for the deferred modes:
DROP INDEX IF EXISTS output_unspent_null_token_category_index;
DROP INDEX IF EXISTS output_unspent_null_search_index;
DROP INDEX IF EXISTS output_unspent_bits_null_token_category_index;
DROP INDEX IF EXISTS output_unspent_bits_null_search_index;
DROP INDEX IF EXISTS output_unspent_bits_token_category_index;
DROP INDEX IF EXISTS output_unspent_bits_search_index;
